# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: '#home'
    weight: 10
  - name: Results
    url: '#results'
    weight: 20
  - name: Sponsors
    url: '#sponsors'
    weight: 30
  - name: Press
    url: '#press'
    weight: 40
  - name: Teams
    url: '#teams'
    weight: 50
  - name: Gallery
    identifier: gallery
    url: '/gallery/'
    weight: 70
  - name: Previous Competitions
    identifier: previous
    weight: 90
  - name: 2022
    parent: previous
    url: '/previous/2022/'
    weight: 10

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/uploads/resume.pdf` and uncomment the lines below.
#  - name: CV
#    url: uploads/resume.pdf
#    weight: 70
